name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clj-kondo checks
      uses: DeLaGuardo/clojure-lint-action@v1
      #with:
        # Arguments to be passed to clj-kondo
        #clj-kondo-args: # default is --lint src
        # Github token to report linter results back to check
        #github_token: 
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
